### ISSUE TITLE
Some files are not under the BSD license, and some files are distributed by violating their license

### ISSUE THREAD

**Issue by olebole** [wlandsman/IDLAstro#10]
The following files document a license that contradicts to the [BSD-2 license](https://opensource.org/licenses/BSD-2-Clause) of the whole package.

`factor.pro`, `getwrd.pro`, `isarray.pro`, `polrec.pro`, `prime.pro`, `recpol.pro`, `repchr.pro`, `sphdist.pro`, and `ymd2dn.pro` have
```
; Copyright (C) 1988, Johns Hopkins University/Applied Physics Laboratory
; This software may be used, copied, or redistributed as long as it is not
; sold and this copyright notice is reproduced on each copy made.  This
; routine is provided as is without any express or implied warranties
; whatsoever.  Other limitations apply as described in the file disclaimer.txt.
```
This license restricts the distribution to not being sold, while the BSD license does not have such a restriction. Also, the file `disclaimer.txt` that is referenced in the copyright notice is missing.

`blkshift.pro`, `jplephinterp.pro`, `jplephread.pro`, `jplephtest.pro`, and `tdb2tdt.pro` have
```
; Copyright (C) 2000, 2002, Craig Markwardt
; This software is provided as is without any warranty whatsoever.
; Permission to use, copy and distribute unmodified copies for
; non-commercial purposes, and to modify and use for personal or
; internal use, is granted.  All other rights are reserved.
```
This license restricts the usage and distribution to non-commercial purposes, while the BSD license does not have this restriction. Also it does not allow the public distribution of modified files.
As the modification history of these files document, this is already violated in the IDLAstro distribution:
```
;   Truncate if moving data block forward from  the end of file 
;             using TRUNCATE_LUN   W. Landsman Feb. 2005 
;   Assume since V5.5, remove VMS support  W. Landsman  Sep 2006
;   Assume since V5.6, TRUNCATE_LUN available  W. Landsman Sep 2006
;   MacOS can point beyond EOF    W. Landsman   Aug 2009
;   Use V6.0 notation  W. Landsman Aprl 2014
```

`eqpole_grid.pro`, `qdcb_grid.pro`, and `wcs_demo.pro` have
```
;       Copyright 1991, The Regents of the University of California. This
;       software was produced under U.S. Government contract (W-7405-ENG-36)
;       by Los Alamos National Laboratory, which is operated by the
;       University of California for the U.S. Department of Energy.
;       The U.S. Government is licensed to use, reproduce, and distribute
;       this software. Neither the Government nor the University makes
;       any warranty, express or implied, or assumes any liability or
;       responsibility for the use of this software.
```
My interpretation of this license is that usage and distribution is __only__ allowed for the U.S. Government.

These licenses makes it impossible to distribute these files with open source distributions, like Debian. In Debian, there are [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines) that don't allow discrimination against fields of endeavor (point 6).

Could you clarify the licenses of these files? For some of them (`isarray.pro`, `repchr.pro`, `ymd2dn.pro`, ), there is a [replacement in Debian](https://sources.debian.net/src/idlastro/2016.02.25%2Bdfsg-1/debian/patches/provide_free_procedures.patch/).

**Comment by wlandsman** [comment]
Yes, this is not a package but rather a place where routines can be contributed by the community.     So any internal copyrights take precedence over the site information.   

Craig Markwardt gave me permission to maintain future development of blkshift.pro so I have removed his copyright information.
