### ISSUE TITLE
Queryvizier.pro not working anymore

### ISSUE THREAD

**Issue by dnidever** [wlandsman/IDLAstro#29]
I've run into an issue with the IDL Astro user's queryvizier.pro.
It seems that query results from VizieR now end with an INFO
line stating the number of matches, e.g.,

#INFO	matches=636	matching records

But queryvizier.pro (line 236-239) picks this up as an error
and returns nothing.  Would it be possible to fix this?  I think
just removing those lines would do it.

**Comment by wlandsman** [comment]
I will look at this within the next 24 hours
