### ISSUE TITLE
How to make the headers of two fits files the same?

### ISSUE THREAD

**Issue by MiraYugario** [wlandsman/IDLAstro#7]
Infact I have to make the header of fits file 'exponential.fits' same as that of 'empirical.fits'. Is there any way to do it with writefits.pro?Please help

**Comment by MiraYugario** [comment]
Infact I have to make the header of fits file 'exponential.fits' same as that of 'empirical.fits'. Is there any way to do it with writefits.pro?Please help

**Comment by wlandsman** [comment]
Already answered on comp.lang.idl-pvwave
